# Generated by Django 4.2.16 on 2024-10-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('assignee', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('backlog', 'Бэклог'), ('in_progress', 'В процессе'), ('done', 'Выполнено')], default='backlog', max_length=15)),
            ],
        ),
    ]
